export const FETCH_BOOK_LIST_REQUEST = "FETCH_BOOK_LIST_REQUEST"
export const FETCH_BOOK_LIST_SUCCESS = "FETCH_BOOK_LIST_SUCCESS"
export const FETCH_BOOK_LIST_FAILURE = "FETCH_BOOK_LIST_FAILURE"
export const FETCH_SINGLE_BOOK = "FETCH_SINGLE_BOOK"
